# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: package.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class User(betterproto.Message):
    name: str = betterproto.string_field(1)
    email: str = betterproto.string_field(2)
    address: str = betterproto.string_field(3)
